# Generated by Django 2.2.6 on 2019-10-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='desription',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
